import Config.appVersionLink;
import Config.backgroundColor;
import Config.downloadLink;
import Config.fontColor;
import Config.fontName;
import Config.fontSize;
import Config.programFolder;
import Config.version;
import Config.getVersionList;
import Config.hasProgram;
import Config.fallbackProgramFolder;
import Config.fallbackWithoutPostfix;
import Config.startInstallWithSaveAndBar;
import Config.installerVersionLink;
import openfl.Lib.application as app;
import Config.SIDEBAR_WIDTH;